name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build project
      run: ./gradlew build
    - name: Upload test coverage to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Generate documentation
      run: ./gradlew dokkaGfm
    - name: Update documentation
      run: |
        cp -r ./build/dokka/gfm/* ./documentation
        git config --global user.name "GitHub CI"
        git config --global user.email "noreply@github.com"
        git add ./documentation 
        git commit -m "CI: Updated documentation"
        git push
